import mojap_metadata
from mojap_metadata.converters import BaseConverter
import yaml

# mapping MOJAP data types to DLT-compatible types
type_mapping = {
    "string": "text",
    "int64": "bigint",
    "int32": "int",
    "float": "float",
    "float64": "double",
    "boolean": "bool",
    "date": "timestamp",       # MOJAP 'date' mapped to DLT 'timestamp'
    "datetime": "timestamp",   # MOJAP 'datetime' mapped to DLT 'timestamp'
    "timestamp(ms)": "timestamp",
    "timestamp(ns)": "timestamp",
    "timestamp(s)": "timestamp",
    "date64":"timestamp",
    "date32":'date',
    "bool_":"bool",
    "bool":"bool"
}

def convert_metadata_to_dlt(md : mojap_metadata.Metadata) -> dict:
    """
    Converts a MOJAP-style schema directly to a minimal DLT-compatible schema dictionary.
    This version excludes fields that are auto-generated by DLT during pipeline execution.
    """
    
    # convert each column definition from MOJAP to DLT format
    columns = {}
    for field in md.columns:
        keys = list(field)
        name = ''
        for key in keys:
            if key == 'name':
                name = field[key]
                columns[name]={}
            elif key == 'type':

                columns[name][key] = type_mapping.get(field[key]) 
                
                if columns[name][key] is None:
                    print(f'type : {field[key]} not found in type map, defaulting to text ')
                    columns[name][key] = 'text'
            else:
                columns[name][key] = field[key]
    
    # construct the final DLT schema dictionary
    return construct_yaml(md.name,columns)


def construct_yaml(name,columns) -> dict:
    """
    Consructs the final DLT-compatible schema string
    """

    return {
        "name": name,
        "tables": {
            name: {
                "columns": columns,          # include converted column definitions
                "resource": name   # rsource name matches original schema name
            }
        }
    }


def dlt_to_yaml(schema:dict,filepath:str,mode:str = "w"):
    """
    Saves the final DLT-compatible schema to a YAML file in a deaignated location. 
    """

    with open(filepath,mode) as f:
        yaml.safe_dump(schema,f)